DROP TABLE WEATHER03;


CREATE TABLE WEATHER03(
	SEQ INT IDENTITY(1,1) PRIMARY KEY,
	INSERT_TIME DATETIME,
	BASE_DATE CHAR(8) NOT NULL,
	BASE_TIME CHAR(4) NOT NULL,
	T3H CHAR(8),
	REH CHAR(8)
);


INSERT INTO WEATHER03 VALUES(GETDATE(), 20200521,'0900',21,11);


SELECT DISTINCT BASE_DATE, BASE_TIME, T3H, REH FROM WEATHER03 ORDER BY BASE_DATE ASC, BASE_TIME ASC; 


SELECT * FROM WEATHER03;